spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortnerdb
    username: root
    password: akshay
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
    show-sql: true

jwt:
  expiration: 1800000
  secret: xP4h7ZcVQnA3oYdL1tR9Km6BeWfU0JsGvMzXqPb8LiEyTCaNRD5UHgSjFwZo3IkX


#logging:
#  level:
#    org.springframework.security: DEBUG


