spring:
  datasource:
    url:  ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
    show-sql: true


